version: "3.9"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redisVolume:/data
    restart: always
    command: redis-server
  redis-commander:
    image: rediscommander/redis-commander
    restart: always
    environment:
      REDIS_HOST: redis
    links:
    - redis
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresVolume:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: opsbridge
  pgadmin:
    image: dpage/pgadmin4:5
    volumes:
      - pgadminVolume:/var/lib/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: opsbridge
      PGADMIN_LISTEN_PORT: 8080
    links:
    - postgres
  portainer:
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerVolume:/data
    restart: always
  swagger:
    image: swaggerapi/swagger-editor
    restart: always
  nginx:
    build:
      context: nginx
      args:
        - HTTP_PROXY=${HTTP_PROXY}
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
    links:
      - portainer
      - pgadmin
      - redis-commander
      - swagger
    restart: always
    environment:
      HOSTNAME: ${HOSTNAME}
      WSL_IP: ${WSL_IP}
volumes:
  redisVolume: {}
  postgresVolume: {}
  pgadminVolume: {}
  portainerVolume: {}
